version: '3.8'

services:
  k8s-springboot-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: k8s-springboot-dashboard
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - CONFIG_PATH=/app/config.yaml
      - KUBERNETES_IN_CLUSTER=false
    volumes:
      # Mount your own config file if needed
      - ./config.yaml:/app/config.yaml
      # For external kubeconfig
      - ${KUBECONFIG:-~/.kube/config}:/kube/config:ro
    restart: unless-stopped