apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-monitor
  labels:
    app: spring-boot-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-monitor
  template:
    metadata:
      labels:
        app: spring-boot-monitor
    spec:
      containers:
      - name: monitor-app
        image: ${DOCKER_IMAGE_NAME}:${VERSION}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10