apiVersion: v1
kind: Service
metadata:
  name: spring-boot-monitor
  labels:
    app: spring-boot-monitor
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: spring-boot-monitor